#spring:
#  application:
#    name: patient-service
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:patient-service
#    username: hamedmiri
#    password: 85192577
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
#  sql:
#    init:
#      mode: always

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: hamedmiri
    password: 85192577
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always




server:
  port: 4000


logging:
  level:
    root: info

#show standard logs, but skip deep debug stuff



